//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCHLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OCHLib.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;        ///\n&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;        ///\n        ///\n&lt;!-- localized strings --&gt;        ///\n&lt;xsl:variable name=&apos;ColumnHeader_Date&apos;&gt;日期&lt;/xsl:variable&gt;        ///\n&lt;xsl:variable name=&apos;ColumnHeader_Time&apos;&gt;时间&lt;/xsl:variable&gt;        ///\n&lt;xsl:variable name=&apos;ColumnHeader_From&apos;&gt;发送者&lt;/xsl:variable&gt;        ///\n&lt;xsl:variable name=&apos;ColumnHeader_To&apos;&gt;接收者&lt;/xsl:variable&gt;        ///\n&lt;xsl:variable name=&apos;ColumnHeader_Message&apos;&gt;消息&lt;/xsl:variable&gt;        ///\n        ///\n&lt;!-- variables --&gt;        ///\n&lt;xsl:variable name=&apos;Debug&apos;&gt;0&lt;/xsl:variable&gt;        ///\n        ///\n&lt;xs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MessageLog {
            get {
                return ResourceManager.GetString("MessageLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Urgent Interruptions.
        /// </summary>
        internal static string MISTATUS_ALLOW_URGENT_INTERRUPTIONS {
            get {
                return ResourceManager.GetString("MISTATUS_ALLOW_URGENT_INTERRUPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away.
        /// </summary>
        internal static string MISTATUS_AWAY {
            get {
                return ResourceManager.GetString("MISTATUS_AWAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be right back.
        /// </summary>
        internal static string MISTATUS_BE_RIGHT_BACK {
            get {
                return ResourceManager.GetString("MISTATUS_BE_RIGHT_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        internal static string MISTATUS_BLOCKED {
            get {
                return ResourceManager.GetString("MISTATUS_BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        internal static string MISTATUS_BUSY {
            get {
                return ResourceManager.GetString("MISTATUS_BUSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string MISTATUS_CUSTOM {
            get {
                return ResourceManager.GetString("MISTATUS_CUSTOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not disturb.
        /// </summary>
        internal static string MISTATUS_DO_NOT_DISTURB {
            get {
                return ResourceManager.GetString("MISTATUS_DO_NOT_DISTURB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        internal static string MISTATUS_IDLE {
            get {
                return ResourceManager.GetString("MISTATUS_IDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a conference.
        /// </summary>
        internal static string MISTATUS_IN_A_CONFERENCE {
            get {
                return ResourceManager.GetString("MISTATUS_IN_A_CONFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a meeting.
        /// </summary>
        internal static string MISTATUS_IN_A_MEETING {
            get {
                return ResourceManager.GetString("MISTATUS_IN_A_MEETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string MISTATUS_INVISIBLE {
            get {
                return ResourceManager.GetString("MISTATUS_INVISIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May be available.
        /// </summary>
        internal static string MISTATUS_MAY_BE_AVAILABLE {
            get {
                return ResourceManager.GetString("MISTATUS_MAY_BE_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string MISTATUS_OFFLINE {
            get {
                return ResourceManager.GetString("MISTATUS_OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a call.
        /// </summary>
        internal static string MISTATUS_ON_THE_PHONE {
            get {
                return ResourceManager.GetString("MISTATUS_ON_THE_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string MISTATUS_ONLINE {
            get {
                return ResourceManager.GetString("MISTATUS_ONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of the office.
        /// </summary>
        internal static string MISTATUS_OUT_OF_OFFICE {
            get {
                return ResourceManager.GetString("MISTATUS_OUT_OF_OFFICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out to lunch.
        /// </summary>
        internal static string MISTATUS_OUT_TO_LUNCH {
            get {
                return ResourceManager.GetString("MISTATUS_OUT_TO_LUNCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string MISTATUS_UNKNOWN {
            get {
                return ResourceManager.GetString("MISTATUS_UNKNOWN", resourceCulture);
            }
        }
    }
}
